# -*- coding: utf-8 -*-
from functools import partial

import scrapy

from utils.logging import *

from ..base import CosmelSpider
from cosmel_scrapy.db import Db
from cosmel_scrapy.items.cosmel import *

class Spider(scrapy.Spider, CosmelSpider):
    name = '_'.join(__name__.split('.')[-2:])

    def start_requests(self):
        db = Db(self)

        db.execute('SELECT id, alias FROM cosmel.brand_alias ORDER BY id')
        self.skip_set_brand_alias = {bbalias: bid for (bid, bbalias,) in db.fetchall()}

        db.execute('SELECT id, orig_name FROM cosmel.brand ORDER BY id')
        res = db.fetchall()

        del db

        bid2bname = {}

        for (bid, bname,) in res:
            # logger().spam((bid, bname,))
            bid2bname[bid] = bname

        # Check typo
        for (bid, bname, bbalias,) in self.alias_list:
            assert bid2bname[bid] == bname, (bid, bname, bbalias,)

        # Items
        items = []
        for (bid, bname, bbalias,) in self.alias_list:
            logger().info(f'{bid} {bname} <- {bbalias}')
            if bid != self.skip_set_brand_alias.get(bbalias):
                items.append(
                    BrandAliasItem(
                        id    = bid,
                        alias = bbalias,
                    )
                )

        yield from self.do_items(*items)


    # From cosmel.bin.task.repo.run_brand_alias
    alias_list = [
        (8, 'ORIGINS 品木宣言', 'origins'),
        (8, 'ORIGINS 品木宣言', '品木宣言'),
        (11, 'SHISEIDO 資生堂', 'shiseido'),
        (11, 'SHISEIDO 資生堂', '資生堂'),
        (11, 'SHISEIDO 資生堂', '資生堂國際櫃'),
        (11, 'SHISEIDO 資生堂', '資生堂東京櫃'),
        (11, 'SHISEIDO 資生堂', '資生堂開架式'),
        (14, "kiehl's 契爾氏", 'kiehl'),
        (14, "kiehl's 契爾氏", 'kiehls'),
        (14, "kiehl's 契爾氏", '契爾氏'),
        (17, 'shu uemura 植村秀', 'shuuemura'),
        (17, 'shu uemura 植村秀', 'shu□uemura'),
        (17, 'shu uemura 植村秀', '植村秀'),
        (20, 'KOSE 高絲', 'clearturn'),
        (20, 'KOSE 高絲', 'clear□turn'),
        (20, 'KOSE 高絲', 'kose'),
        (20, 'KOSE 高絲', '高絲'),
        (23, 'LANEIGE 蘭芝', 'laneige'),
        (23, 'LANEIGE 蘭芝', '蘭芝'),
        (26, 'SK-II', 'sk2'),
        (26, 'SK-II', 'skii'),
        (26, 'SK-II', 'sk□ii'),
        (32, 'IPSA 茵芙莎', 'ipsa'),
        (32, 'IPSA 茵芙莎', '茵芙莎'),
        (35, 'LANCÔME 蘭蔻', 'lancome'),
        (35, 'LANCÔME 蘭蔻', '蘭蔻'),
        (37, 'ESTÉE LAUDER 雅詩蘭黛', 'esteelauder'),
        (37, 'ESTÉE LAUDER 雅詩蘭黛', 'estee□lauder'),
        (37, 'ESTÉE LAUDER 雅詩蘭黛', '雅詩蘭黛'),
        (40, 'sisley 希思黎', 'sisley'),
        (40, 'sisley 希思黎', '希思黎'),
        (43, 'CLARINS 克蘭詩', 'clarins'),
        (43, 'CLARINS 克蘭詩', '克蘭詩'),
        (46, 'GUERLAIN 嬌蘭', 'guerlain'),
        (46, 'GUERLAIN 嬌蘭', '嬌蘭'),
        (49, 'Clarisonic 科萊麗', 'clarisonic'),
        (49, 'Clarisonic 科萊麗', '科萊麗'),
        (52, 'YSL 聖羅蘭', 'ysl'),
        (52, 'YSL 聖羅蘭', '聖羅蘭'),
        (55, 'BOBBI BROWN 芭比布朗', 'bobbibrown'),
        (55, 'BOBBI BROWN 芭比布朗', 'bobbi□brown'),
        (55, 'BOBBI BROWN 芭比布朗', '芭比布朗'),
        (58, 'Sulwhasoo 雪花秀', 'sulwhasoo'),
        (58, 'Sulwhasoo 雪花秀', '雪花秀'),
        (61, 'cle de peau beaute 肌膚之鑰', 'cledepeaubeaute'),
        (61, 'cle de peau beaute 肌膚之鑰', 'cle□de□peau□beaute'),
        (61, 'cle de peau beaute 肌膚之鑰', '肌膚之鑰'),
        (64, 'M.A.C', 'mac'),
        (64, 'M.A.C', 'm□a□c'),
        (67, 'kanebo 佳麗寶', 'kanebo'),
        (67, 'kanebo 佳麗寶', '佳麗寶'),
        (70, 'DECORTE 黛珂', 'decorte'),
        (70, 'DECORTE 黛珂', '黛珂'),
        (73, 'Dior 迪奧', 'dior'),
        (73, 'Dior 迪奧', '迪奧'),
        (76, 'GIORGIO ARMANI 亞曼尼', 'giorgioarmani'),
        (76, 'GIORGIO ARMANI 亞曼尼', 'giorgio□armani'),
        (76, 'GIORGIO ARMANI 亞曼尼', '亞曼尼'),
        (79, 'NARS', 'nars'),
        (82, 'JILL STUART 吉麗絲朵', 'jillstuart'),
        (82, 'JILL STUART 吉麗絲朵', 'jill□stuart'),
        (82, 'JILL STUART 吉麗絲朵', '吉麗絲朵'),
        (88, 'BIOTHERM 碧兒泉', 'biotherm'),
        (88, 'BIOTHERM 碧兒泉', '碧兒泉'),
        (91, 'CLINIQUE 倩碧', 'clinique'),
        (91, 'CLINIQUE 倩碧', '倩碧'),
        (94, 'ALBION 艾倫比亞', 'albion'),
        (94, 'ALBION 艾倫比亞', '艾倫比亞'),
        (109, 'ettusais 艾杜紗', 'ettusais'),
        (109, 'ettusais 艾杜紗', '艾杜紗'),
        (112, 'RMK', 'rmk'),
        (124, 'Whoo 后', 'whoo'),
        (124, 'Whoo 后', '后'),
        (127, 'ERNO LASZLO 奧倫納素', 'ernolaszlo'),
        (127, 'ERNO LASZLO 奧倫納素', 'erno□laszlo'),
        (127, 'ERNO LASZLO 奧倫納素', '奧倫納素'),
        (133, 'KRYOLAN 歌劇魅影', 'kryolan'),
        (133, 'KRYOLAN 歌劇魅影', '歌劇魅影'),
        (142, 'SOFINA 蘇菲娜', 'sofina'),
        (142, 'SOFINA 蘇菲娜', '蘇菲娜'),
        (145, 'THE BODY SHOP 美體小舖', 'thebodyshop'),
        (145, 'THE BODY SHOP 美體小舖', 'the□body□shop'),
        (145, 'THE BODY SHOP 美體小舖', '美體小舖'),
        (148, 'Melvita 蜜葳特', 'melvita'),
        (148, 'Melvita 蜜葳特', '蜜葳特'),
        (151, 'THREE', 'three'),
        (154, 'Crabtree & Evelyn 瑰珀翠', 'crabtreeevelyn'),
        (154, 'Crabtree & Evelyn 瑰珀翠', 'crabtree□evelyn'),
        (154, 'Crabtree & Evelyn 瑰珀翠', '瑰珀翠'),
        (157, 'MOROCCANOIL', 'moroccanoil'),
        (160, 'AVEDA 肯夢', 'aveda'),
        (160, 'AVEDA 肯夢', '肯夢'),
        (163, 'Chloé', 'chloe'),
        (166, 'CHIC CHOC 奇可俏可', 'chicchoc'),
        (166, 'CHIC CHOC 奇可俏可', 'chic□choc'),
        (166, 'CHIC CHOC 奇可俏可', '奇可俏可'),
        (169, 'DARPHIN 朵法', 'darphin'),
        (169, 'DARPHIN 朵法', '朵法'),
        (172, 'LA MER 海洋拉娜', 'lamer'),
        (172, 'LA MER 海洋拉娜', 'la□mer'),
        (172, 'LA MER 海洋拉娜', '海洋拉娜'),
        (175, 'innisfree', 'innisfree'),
        (178, 'EVE LOM', 'evelom'),
        (178, 'EVE LOM', 'eve□lom'),
        (181, 'ReVive 麗膚再生', 'revive'),
        (181, 'ReVive 麗膚再生', '麗膚再生'),
        (184, "L'OCCITANE 歐舒丹", 'loccitane'),
        (184, "L'OCCITANE 歐舒丹", 'missloccitane'),
        (184, "L'OCCITANE 歐舒丹", 'miss□loccitane'),
        (184, "L'OCCITANE 歐舒丹", '歐舒丹'),
        (187, 'la prairie', 'laprairie'),
        (187, 'la prairie', 'la□prairie'),
        (190, 'Chantecaille 香緹卡', 'chantecaille'),
        (190, 'Chantecaille 香緹卡', '香緹卡'),
        (193, 'FANCL', 'fancl'),
        (196, 'Elizabeth Arden 伊麗莎白雅頓', 'elizabetharden'),
        (196, 'Elizabeth Arden 伊麗莎白雅頓', 'elizabeth□arden'),
        (196, 'Elizabeth Arden 伊麗莎白雅頓', '伊麗莎白雅頓'),
        (199, 'benefit', 'benefit'),
        (202, 'PAUL & JOE', 'pauljoe'),
        (202, 'PAUL & JOE', 'paul□joe'),
        (205, 'Les Merveilleuses LADUREE', 'lesmerveilleusesladuree'),
        (205, 'Les Merveilleuses LADUREE', 'les□merveilleuses□laduree'),
        (208, 'ANNA SUI 安娜蘇', 'annasui'),
        (208, 'ANNA SUI 安娜蘇', 'anna□sui'),
        (208, 'ANNA SUI 安娜蘇', '安娜蘇'),
        (211, 'GIVENCHY 紀梵希', 'givenchy'),
        (211, 'GIVENCHY 紀梵希', '紀梵希'),
        (214, 'MAKE UP FOR EVER', 'makeupforever'),
        (214, 'MAKE UP FOR EVER', 'make□up□for□ever'),
        (226, 'Jurlique 茱莉蔻', 'jurlique'),
        (226, 'Jurlique 茱莉蔻', '茱莉蔻'),
        (265, 'laura mercier 蘿拉蜜思', 'lauramercier'),
        (265, 'laura mercier 蘿拉蜜思', 'laura□mercier'),
        (265, 'laura mercier 蘿拉蜜思', '蘿拉蜜思'),
        (283, 'Aesop', 'aesop'),
        (307, 'banila co.', 'banilaco'),
        (307, 'banila co.', 'banila□co'),
        (310, 'diptyque', 'diptyque'),
        (313, 'VICHY 薇姿', 'vichy'),
        (313, 'VICHY 薇姿', '薇姿'),
        (331, 'divinia 蒂芬妮亞', 'divinia'),
        (331, 'divinia 蒂芬妮亞', '蒂芬妮亞'),
        (334, 'Avene 雅漾', 'avene'),
        (334, 'Avene 雅漾', '雅漾'),
        (337, 'DHC', 'dhc'),
        (340, 'noreva 法國歐德瑪', 'noreva'),
        (340, 'noreva 法國歐德瑪', '法國歐德瑪'),
        (343, 'DR.WU 達爾膚', 'drwu'),
        (343, 'DR.WU 達爾膚', 'dr□wu'),
        (343, 'DR.WU 達爾膚', '達爾膚'),
        (346, 'FOR BELOVED ONE 寵愛之名', 'forbelovedone'),
        (346, 'FOR BELOVED ONE 寵愛之名', 'for□beloved□one'),
        (346, 'FOR BELOVED ONE 寵愛之名', '寵愛之名'),
        (349, 'Biore 蜜妮', 'biore'),
        (349, 'Biore 蜜妮', '蜜妮'),
        (352, 'NEUTROGENA 露得清', 'neutrogena'),
        (352, 'NEUTROGENA 露得清', '露得清'),
        (355, "POND'S 旁氏", 'pond'),
        (355, "POND'S 旁氏", 'ponds'),
        (355, "POND'S 旁氏", '旁氏'),
        (358, '專科', '專科'),
        (361, 'MENTHOLATUM 曼秀雷敦', 'mentholatum'),
        (361, 'MENTHOLATUM 曼秀雷敦', '曼秀雷敦'),
        (364, 'Curel 珂潤', 'curel'),
        (364, 'Curel 珂潤', '珂潤'),
        (367, 'sebamed 施巴', 'sebamed'),
        (367, 'sebamed 施巴', '施巴'),
        (370, 'Hada-Labo 肌研', 'hadalabo'),
        (370, 'Hada-Labo 肌研', 'hada□labo'),
        (370, 'Hada-Labo 肌研', '肌研'),
        (373, 'NARUKO', 'naruko'),
        (376, 'Dove 多芬', 'dove'),
        (376, 'Dove 多芬', '多芬'),
        (379, 'Bio-essence 碧歐斯', 'bioessence'),
        (379, 'Bio-essence 碧歐斯', 'bio□essence'),
        (379, 'Bio-essence 碧歐斯', '碧歐斯'),
        (382, 'am+pm skincare', 'ampmskincare'),
        (382, 'am+pm skincare', 'am□pm□skincare'),
        (385, 'NEOGENCE 霓淨思', 'neogence'),
        (385, 'NEOGENCE 霓淨思', '霓淨思'),
        (388, "L'EGERE 蘭吉兒", 'legere'),
        (388, "L'EGERE 蘭吉兒", '蘭吉兒'),
        (391, "L'OREAL PARIS 巴黎萊雅", 'lorealparis'),
        (391, "L'OREAL PARIS 巴黎萊雅", 'loreal□paris'),
        (391, "L'OREAL PARIS 巴黎萊雅", '巴黎萊雅'),
        (394, 'Cellina 雪芙蘭', 'cellina'),
        (394, 'Cellina 雪芙蘭', '雪芙蘭'),
        (397, 'GARNIER 卡尼爾', 'garnier'),
        (397, 'GARNIER 卡尼爾', '卡尼爾'),
        (400, 'OLAY 歐蕾', 'olay'),
        (400, 'OLAY 歐蕾', '歐蕾'),
        (403, 'NIVEA 妮維雅', 'nivea'),
        (403, 'NIVEA 妮維雅', '妮維雅'),
        (406, 'Dr.Morita 森田藥粧', 'drmorita'),
        (406, 'Dr.Morita 森田藥粧', 'dr□morita'),
        (406, 'Dr.Morita 森田藥粧', '森田藥粧'),
        (409, 'MISSHA', 'missha'),
        (412, 'Beauty Buffet 天天美麗', 'beautybuffet'),
        (412, 'Beauty Buffet 天天美麗', 'beauty□buffet'),
        (412, 'Beauty Buffet 天天美麗', '天天美麗'),
        (415, 'Beautymate 美肌之誌', 'beautymate'),
        (415, 'Beautymate 美肌之誌', '美肌之誌'),
        (418, 'OGUMA 水美媒', 'oguma'),
        (418, 'OGUMA 水美媒', '水美媒'),
        (421, 'KOSE COSMEPORT 蔻絲魅寶', 'kosecosmeport'),
        (421, 'KOSE COSMEPORT 蔻絲魅寶', 'kose□cosmeport'),
        (421, 'KOSE COSMEPORT 蔻絲魅寶', '蔻絲魅寶'),
        (424, 'WHITE FORMULA 自白肌', 'whiteformula'),
        (424, 'WHITE FORMULA 自白肌', 'white□formula'),
        (424, 'WHITE FORMULA 自白肌', '自白肌'),
        (427, 'Vaseline 凡士林', 'vaseline'),
        (427, 'Vaseline 凡士林', '凡士林'),
        (430, 'CARMAX 小蜜媞', 'carmax'),
        (430, 'CARMAX 小蜜媞', '小蜜媞'),
        (433, 'URIAGE 優麗雅', 'uriage'),
        (433, 'URIAGE 優麗雅', '優麗雅'),
        (436, "BURT'S BEES 小蜜蜂爺爺", 'burtbees'),
        (436, "BURT'S BEES 小蜜蜂爺爺", 'burtsbees'),
        (436, "BURT'S BEES 小蜜蜂爺爺", 'burts□bees'),
        (436, "BURT'S BEES 小蜜蜂爺爺", 'burt□bees'),
        (436, "BURT'S BEES 小蜜蜂爺爺", '小蜜蜂爺爺'),
        (439, '3M', '3m'),
        (442, 'MAYBELLINE 媚比琳', 'maybelline'),
        (442, 'MAYBELLINE 媚比琳', '媚比琳'),
        (445, 'INTEGRATE 絕色魅癮', 'integrate'),
        (445, 'INTEGRATE 絕色魅癮', '絕色魅癮'),
        (448, '1028', '1028'),
        (451, 'Freshel 膚蕊', 'freshel'),
        (451, 'Freshel 膚蕊', '膚蕊'),
        (454, 'CLIO 珂莉奧', 'clio'),
        (454, 'CLIO 珂莉奧', '珂莉奧'),
        (457, 'Pure Beauty', 'pinkbypurebeauty'),
        (457, 'Pure Beauty', 'pink□by□pure□beauty'),
        (457, 'Pure Beauty', 'purebeauty'),
        (457, 'Pure Beauty', 'pure□beauty'),
        (460, 'UNT', 'unt'),
        (463, 'Za', 'za'),
        (466, 'KATE 凱婷', 'kate'),
        (466, 'KATE 凱婷', '凱婷'),
        (472, 'media 媚點', 'media'),
        (472, 'media 媚點', '媚點'),
        (475, 'REVLON 露華濃', 'revlon'),
        (475, 'REVLON 露華濃', '露華濃'),
        (478, 'MAJOLICA MAJORCA 戀愛魔鏡', 'majolicamajorca'),
        (478, 'MAJOLICA MAJORCA 戀愛魔鏡', 'majolica□majorca'),
        (478, 'MAJOLICA MAJORCA 戀愛魔鏡', '戀愛魔鏡'),
        (481, 'AQUA LABEL 水之印', 'aqualabel'),
        (481, 'AQUA LABEL 水之印', 'aqua□label'),
        (481, 'AQUA LABEL 水之印', '水之印'),
        (484, 'Junkisei 潤肌精', 'junkisei'),
        (484, 'Junkisei 潤肌精', '潤肌精'),
        (487, 'neuve 惹我', 'fititwhitia'),
        (487, 'neuve 惹我', 'fitit□whitia'),
        (487, 'neuve 惹我', 'neuve'),
        (487, 'neuve 惹我', '惹我'),
        (490, 'Peripera', 'peripera'),
        (493, 'FASIO 菲希歐', 'fasio'),
        (493, 'FASIO 菲希歐', '菲希歐'),
        (496, 'Visée', 'visee'),
        (499, 'dejavu', 'dejavu'),
        (502, 'AZ-LB', 'azlb'),
        (502, 'AZ-LB', 'az□lb'),
        (505, 'CANMAKE', 'canmake'),
        (508, 'KISS ME 奇士美', 'kissme'),
        (508, 'KISS ME 奇士美', 'kiss□me'),
        (508, 'KISS ME 奇士美', '奇士美'),
        (511, 'Anime Cosme', 'animecosme'),
        (511, 'Anime Cosme', 'anime□cosme'),
        (514, 'BOURJOIS 妙巴黎', 'bourjois'),
        (514, 'BOURJOIS 妙巴黎', '妙巴黎'),
        (517, 'PON PON 澎澎', 'ponpon'),
        (517, 'PON PON 澎澎', 'pon□pon'),
        (517, 'PON PON 澎澎', '澎澎'),
        (520, "Johnson's 嬌生", 'johnson'),
        (520, "Johnson's 嬌生", 'johnsons'),
        (520, "Johnson's 嬌生", '嬌生'),
        (523, 'IBL 依必朗', 'ibl'),
        (523, 'IBL 依必朗', '依必朗'),
        (526, 'WATSONSSKIN 屈臣氏', 'watsonsskin'),
        (526, 'WATSONSSKIN 屈臣氏', '屈臣氏'),
        (529, 'Kamill', 'kamill'),
        (532, 'eos 伊歐詩', 'eos'),
        (532, 'eos 伊歐詩', '伊歐詩'),
        (535, 'Face Queen 絕世愛美肌', 'facequeen'),
        (535, 'Face Queen 絕世愛美肌', 'face□queen'),
        (535, 'Face Queen 絕世愛美肌', '絕世愛美肌'),
        (538, 'PRADA', 'prada'),
        (541, 'too cool for school', 'toocoolforschool'),
        (541, 'too cool for school', 'too□cool□for□school'),
        (544, 'VALENTINO 范倫鐵諾', 'valentino'),
        (544, 'VALENTINO 范倫鐵諾', '范倫鐵諾'),
        (547, 'NEOM', 'neom'),
        (550, 'BYREDO', 'byredo'),
        (553, 'BURBERRY', 'burberry'),
        (556, 'by Terry', 'byterry'),
        (556, 'by Terry', 'by□terry'),
        (559, 'ETVOS', 'etvos'),
        (562, 'Marc Jacobs', 'marcjacobs'),
        (562, 'Marc Jacobs', 'marc□jacobs'),
        (565, 'Rodial', 'rodial'),
        (568, 'BVLGARI 寶格麗', 'bvlgari'),
        (568, 'BVLGARI 寶格麗', '寶格麗'),
        (571, 'Eyeko', 'eyeko'),
        (574, 'Premier', 'premier'),
        (577, 'Elemis', 'elemis'),
        (580, 'Locherber 樂凱博', 'locherber'),
        (580, 'Locherber 樂凱博', '樂凱博'),
        (583, 'miu miu', 'miumiu'),
        (583, 'miu miu', 'miu□miu'),
        (586, 'john masters organics', 'johnmastersorganics'),
        (586, 'john masters organics', 'john□masters□organics'),
        (592, 'SUQQU', 'suqqu'),
        (595, 'dermalogica 德卡', 'dermalogica'),
        (595, 'dermalogica 德卡', '德卡'),
        (598, 'MA CHÉRIE 瑪宣妮', 'macherie'),
        (598, 'MA CHÉRIE 瑪宣妮', 'ma□cherie'),
        (598, 'MA CHÉRIE 瑪宣妮', '瑪宣妮'),
        (601, 'Valmont 法兒曼', 'valmont'),
        (601, 'Valmont 法兒曼', '法兒曼'),
        (604, 'Van Cleef & Arpels 梵克雅寶', 'vancleefarpels'),
        (604, 'Van Cleef & Arpels 梵克雅寶', 'van□cleef□arpels'),
        (604, 'Van Cleef & Arpels 梵克雅寶', '梵克雅寶'),
        (607, 'VERSACE 凡賽斯', 'versace'),
        (607, 'VERSACE 凡賽斯', '凡賽斯'),
        (610, 'Tory Burch', 'toryburch'),
        (610, 'Tory Burch', 'tory□burch'),
        (613, 'TSUBAKI 思波綺', 'tsubaki'),
        (613, 'TSUBAKI 思波綺', '思波綺'),
        (616, 'Salvatore Ferragamo', 'salvatoreferragamo'),
        (616, 'Salvatore Ferragamo', 'salvatore□ferragamo'),
        (619, 'Rene Furterer 荷那法蕊', 'renefurterer'),
        (619, 'Rene Furterer 荷那法蕊', 'rene□furterer'),
        (619, 'Rene Furterer 荷那法蕊', '荷那法蕊'),
        (622, 'REN', 'ren'),
        (625, 'PHILIPS 飛利浦', 'philips'),
        (625, 'PHILIPS 飛利浦', '飛利浦'),
        (628, 'NEO-TEC 妮傲絲翠', 'neotec'),
        (628, 'NEO-TEC 妮傲絲翠', 'neo□tec'),
        (628, 'NEO-TEC 妮傲絲翠', '妮傲絲翠'),
        (631, 'uka', 'uka'),
        (634, 'Neal’s Yard Remedies 尼爾氏香芬庭園', 'nealsyardremedies'),
        (634, 'Neal’s Yard Remedies 尼爾氏香芬庭園', 'neals□yard□remedies'),
        (634, 'Neal’s Yard Remedies 尼爾氏香芬庭園', 'nealyardremedies'),
        (634, 'Neal’s Yard Remedies 尼爾氏香芬庭園', 'neal□yard□remedies'),
        (634, 'Neal’s Yard Remedies 尼爾氏香芬庭園', '尼爾氏香芬庭園'),
        (637, 'rahua', 'rahua'),
        (640, 'BeautyMaker', 'beautymaker'),
        (643, 'ETUDE HOUSE', 'etudehouse'),
        (643, 'ETUDE HOUSE', 'etude□house'),
        (646, 'JO MALONE LONDON', 'jomalonelondon'),
        (646, 'JO MALONE LONDON', 'jo□malone□london'),
        (649, 'KAI DELUXE 型色大師', 'kaideluxe'),
        (649, 'KAI DELUXE 型色大師', 'kai□deluxe'),
        (649, 'KAI DELUXE 型色大師', '型色大師'),
        (652, 'CHANEL 香奈兒', 'chanel'),
        (652, 'CHANEL 香奈兒', '香奈兒'),
        (655, 'ALTERNA', 'alterna'),
        (658, 'KLORANE 蔻蘿蘭', 'klorane'),
        (658, 'KLORANE 蔻蘿蘭', '蔻蘿蘭'),
        (661, 'Omorovicza', 'omorovicza'),
        (664, 'Kérastase 巴黎卡詩', 'kerastase'),
        (664, 'Kérastase 巴黎卡詩', '巴黎卡詩'),
        (667, 'Bondi Wash', 'bondiwash'),
        (667, 'Bondi Wash', 'bondi□wash'),
        (670, 'Fresh Line', 'freshline'),
        (670, 'Fresh Line', 'fresh□line'),
        (676, 'LA ROCHE-POSAY 理膚寶水', 'larocheposay'),
        (676, 'LA ROCHE-POSAY 理膚寶水', 'la□roche□posay'),
        (676, 'LA ROCHE-POSAY 理膚寶水', '理膚寶水'),
        (679, 'LSY 林三益', 'lsy'),
        (679, 'LSY 林三益', '林三益'),
        (682, 'Marykay 玫琳凱', 'marykay'),
        (682, 'Marykay 玫琳凱', '玫琳凱'),
        (688, 'ORBIS', 'orbis'),
        (691, 'philosophy 肌膚哲理', 'philosophy'),
        (691, 'philosophy 肌膚哲理', '肌膚哲理'),
        (694, 'Erborian 艾博妍', 'erborian'),
        (694, 'Erborian 艾博妍', '艾博妍'),
        (703, 'AVIVA', 'aviva'),
        (706, 'DERMEDIC', 'dermedic'),
        (709, 'Bioderma 法國貝德瑪', 'bioderma'),
        (709, 'Bioderma 法國貝德瑪', '法國貝德瑪'),
        (715, 'AZZEEN 芝妍', 'azzeen'),
        (715, 'AZZEEN 芝妍', '芝妍'),
        (718, 'INNER SKIN', 'innerskin'),
        (718, 'INNER SKIN', 'inner□skin'),
        (721, 'AYURA 東洋美學', 'ayura'),
        (721, 'AYURA 東洋美學', '東洋美學'),
        (733, 'ESPRIQUE', 'esprique'),
        (736, 'For Beloved Girl 寵愛女孩', 'forbelovedgirl'),
        (736, 'For Beloved Girl 寵愛女孩', 'for□beloved□girl'),
        (736, 'For Beloved Girl 寵愛女孩', '寵愛女孩'),
        (739, 'DERM iNSTITUTE 得因特', 'derminstitute'),
        (739, 'DERM iNSTITUTE 得因特', 'derm□institute'),
        (739, 'DERM iNSTITUTE 得因特', '得因特'),
        (742, 'FRUSIRNANA 美膚娜娜', 'frusirnana'),
        (742, 'FRUSIRNANA 美膚娜娜', '美膚娜娜'),
        (757, 'BEVY C 妝前保養', 'bevyc'),
        (757, 'BEVY C 妝前保養', 'bevy□c'),
        (757, 'BEVY C 妝前保養', '妝前保養'),
        (763, 'absolution', 'absolution'),
        (766, 'BECCA', 'becca'),
        (781, '我的美麗日記', '我的美麗日記'),
        (784, 'SAUGELLA 賽吉兒', 'saugella'),
        (784, 'SAUGELLA 賽吉兒', '賽吉兒'),
        (793, 'DKNY', 'dkny'),
        (796, 'Tommy Hilfiger', 'tommyhilfiger'),
        (796, 'Tommy Hilfiger', 'tommy□hilfiger'),
        (802, 'Smith & Cult', 'smithcult'),
        (802, 'Smith & Cult', 'smith□cult'),
        (808, 'IOPE', 'iope'),
        (820, 'BELLABEAUTY', 'bellabeauty'),
        (823, 'HIKARU 喜凱露', 'hikaru'),
        (823, 'HIKARU 喜凱露', '喜凱露'),
        (826, 'SRBEAUTY', 'srbeauty'),
        (829, 'CEZANNE', 'cezanne'),
        (835, 'KBEAUTY', 'kbeauty'),
        (838, 'CHRONO AFFECTION 時間寵愛', 'chronoaffection'),
        (838, 'CHRONO AFFECTION 時間寵愛', 'chrono□affection'),
        (838, 'CHRONO AFFECTION 時間寵愛', '時間寵愛'),
        (844, '廣源良', '廣源良'),
        (847, 'Collagen', 'collagen'),
        (850, 'LOVECODE', 'lovecode'),
        (859, 'AZPLAZA', 'azplaza'),
        (862, 'CAUDALIE', 'caudalie'),
        (865, 'AVALON', 'avalon'),
        (868, 'EQUILIBRA 義貝拉', 'equilibra'),
        (868, 'EQUILIBRA 義貝拉', 'perlabella'),
        (868, 'EQUILIBRA 義貝拉', 'syrio'),
        (868, 'EQUILIBRA 義貝拉', '義貝拉'),
        (871, 'DR.BRONNER’S 布朗博士', 'drbronner'),
        (871, 'DR.BRONNER’S 布朗博士', 'drbronners'),
        (871, 'DR.BRONNER’S 布朗博士', 'dr□bronner'),
        (871, 'DR.BRONNER’S 布朗博士', 'dr□bronners'),
        (871, 'DR.BRONNER’S 布朗博士', '布朗博士'),
        (874, 'SKIN Advanced', 'skinadvanced'),
        (874, 'SKIN Advanced', 'skin□advanced'),
        (877, 'Dr.Organic', 'drorganic'),
        (877, 'Dr.Organic', 'dr□organic'),
        (880, 'THE FACE SHOP 菲詩小舖', 'thefaceshop'),
        (880, 'THE FACE SHOP 菲詩小舖', 'the□face□shop'),
        (880, 'THE FACE SHOP 菲詩小舖', '菲詩小舖'),
        (883, 'Revlis', 'revlis'),
        (886, 'Country & Stream', 'countrystream'),
        (886, 'Country & Stream', 'country□stream'),
        (889, 'BIONIKE', 'bionike'),
        (892, 'Jericho', 'jericho'),
        (895, "PALMER'S 帕瑪氏", 'palmer'),
        (895, "PALMER'S 帕瑪氏", 'palmers'),
        (895, "PALMER'S 帕瑪氏", '帕瑪氏'),
        (898, 'Claire’s 格麗', 'claire'),
        (898, 'Claire’s 格麗', 'claires'),
        (898, 'Claire’s 格麗', '格麗'),
        (901, 'BEAUTIA 倍立雅', 'beautia'),
        (901, 'BEAUTIA 倍立雅', '倍立雅'),
        (904, 'Dr.Satin', 'drsatin'),
        (904, 'Dr.Satin', 'dr□satin'),
        (910, 'CETAPHIL 舒特膚', 'cetaphil'),
        (910, 'CETAPHIL 舒特膚', '舒特膚'),
        (913, 'ALOEDERMA 璦露德瑪', 'aloederma'),
        (913, 'ALOEDERMA 璦露德瑪', '璦露德瑪'),
        (919, 'Absolute New York 絕色紐約', 'absolutenewyork'),
        (919, 'Absolute New York 絕色紐約', 'absolute□new□york'),
        (919, 'Absolute New York 絕色紐約', '絕色紐約'),
        (922, 'Hope Girl', 'hopegirl'),
        (922, 'Hope Girl', 'hope□girl'),
        (925, 'A’PIEU', 'apieu'),
        (928, 'VDL', 'vdl'),
        (931, 'Numis med 樂美思', 'numismed'),
        (931, 'Numis med 樂美思', 'numis□med'),
        (931, 'Numis med 樂美思', '樂美思'),
        (934, 'alkmene', 'alkmene'),
        (946, 'CHAPEX 喬沛詩', 'chapex'),
        (946, 'CHAPEX 喬沛詩', '喬沛詩'),
        (949, 'DCS', 'dcs'),
        (952, 'YUSKIN 悠斯晶', 'yuskin'),
        (952, 'YUSKIN 悠斯晶', '悠斯晶'),
        (961, 'Badger 蓓喆', 'badger'),
        (961, 'Badger 蓓喆', '蓓喆'),
        (964, 'CNP LABORATORY', 'cnplaboratory'),
        (964, 'CNP LABORATORY', 'cnp□laboratory'),
        (967, 'NACOLA', 'nacola'),
        (970, 'MEMEBOX', 'immeme'),
        (970, 'MEMEBOX', 'im□meme'),
        (970, 'MEMEBOX', 'memebox'),
        (970, 'MEMEBOX', 'pony'),
        (970, 'MEMEBOX', 'ponyeffect'),
        (970, 'MEMEBOX', 'ponymemebox'),
        (970, 'MEMEBOX', 'ponyxmemebox'),
        (970, 'MEMEBOX', 'pony□effect'),
        (970, 'MEMEBOX', 'pony□memebox'),
        (970, 'MEMEBOX', 'pony□x□memebox'),
        (970, 'MEMEBOX', '女王'),
        (973, '奢華寶貝', '奢華寶貝'),
        (976, '西班牙Babaria', 'babaria'),
        (976, '西班牙Babaria', 'babariababaria'),
        (976, '西班牙Babaria', 'babaria□babaria'),
        (976, '西班牙Babaria', '西班牙'),
        (979, 'MOTE', 'mote'),
        (982, 'heme', 'heme'),
        (985, 'FORENCOS', 'forencos'),
        (988, 'PURE SMILE', 'puresmile'),
        (988, 'PURE SMILE', 'pure□smile'),
        (994, 'BBIA', 'bbia'),
        (997, '3CE', '3ce'),
        (1003, 'eSpoir', 'espoir'),
        (1006, 'St.Clare 聖克萊爾', 'stclare'),
        (1006, 'St.Clare 聖克萊爾', 'st□clare'),
        (1006, 'St.Clare 聖克萊爾', '聖克萊爾'),
        (1012, 'pHisoDerm 菲蘇德美', 'phisoderm'),
        (1012, 'pHisoDerm 菲蘇德美', '菲蘇德美'),
        (1015, 'CHATEAU LABIOTTE', 'chateaulabiotte'),
        (1015, 'CHATEAU LABIOTTE', 'chateau□labiotte'),
        (1018, 'MIO', 'mio'),
        (1021, '陽農園', '陽農園'),
        (1024, 'Clean & Clear 可伶可俐', 'cleanclear'),
        (1024, 'Clean & Clear 可伶可俐', 'clean□clear'),
        (1024, 'Clean & Clear 可伶可俐', '可伶可俐'),
        (1027, 'TONYMOLY', 'tonymoly'),
        (1033, 'BEYOND', 'beyond'),
        (1039, 'AROA', 'aroa'),
        (1042, 'YOUBEST 優倍多', 'youbest'),
        (1042, 'YOUBEST 優倍多', '優倍多'),
        (1045, 'JINGCHENG 京城之霜', 'jingcheng'),
        (1045, 'JINGCHENG 京城之霜', '京城之霜'),
        (1048, 'APRIL SKIN', 'aprilskin'),
        (1048, 'APRIL SKIN', 'april□skin'),
        (1051, 'Dermaction', 'dermaction'),
        (1054, 'SwissVita 瑞士薇佳', 'swissvita'),
        (1054, 'SwissVita 瑞士薇佳', '瑞士薇佳'),
        (1060, 'EVOLU 艾芙洛', 'evolu'),
        (1060, 'EVOLU 艾芙洛', '艾芙洛'),
        (1063, 'Dr. Jart+', 'drjart'),
        (1063, 'Dr. Jart+', 'dr□jart'),
        (1066, 'CHLITINA 克麗緹娜', 'chlitina'),
        (1066, 'CHLITINA 克麗緹娜', '克麗緹娜'),
        (1069, 'ONCE', 'once'),
        (1072, 'Jumelle 佐媚朵爾', 'jumelle'),
        (1072, 'Jumelle 佐媚朵爾', '佐媚朵爾'),
        (1075, 'Rebecca Bonbon', 'rebeccabonbon'),
        (1075, 'Rebecca Bonbon', 'rebecca□bonbon'),
        (1081, 'Hupanique 涵沛', 'hupanique'),
        (1081, 'Hupanique 涵沛', '涵沛'),
        (1084, 'Institut Karite Paris 巴黎乳油木', 'institutkariteparis'),
        (1084, 'Institut Karite Paris 巴黎乳油木', 'institut□karite□paris'),
        (1084, 'Institut Karite Paris 巴黎乳油木', '巴黎乳油木'),
        (1087, 'webner 葦柏納', 'webner'),
        (1087, 'webner 葦柏納', '葦柏納'),
        (1090, 'CHICA Y CHICO', 'chicaychico'),
        (1090, 'CHICA Y CHICO', 'chica□y□chico'),
        (1096, 'DERMAL', 'dermal'),
        (1099, 'HIMALAYA 喜瑪拉雅', 'himalaya'),
        (1099, 'HIMALAYA 喜瑪拉雅', '喜瑪拉雅'),
        (1102, 'Softymo 絲芙蒂', 'softymo'),
        (1102, 'Softymo 絲芙蒂', '絲芙蒂'),
        (1105, 'MEGUSTAME 美愛美', 'megustame'),
        (1105, 'MEGUSTAME 美愛美', '美愛美'),
        (1108, 'SKINLIFE 滋卿愛', 'skinlife'),
        (1108, 'SKINLIFE 滋卿愛', '滋卿愛'),
        (1111, 'FASHION K-BEAUTY', 'fashionkbeauty'),
        (1111, 'FASHION K-BEAUTY', 'fashion□k□beauty'),
        (1114, 'Target PRO by Watsons', 'targetprobywatsons'),
        (1114, 'Target PRO by Watsons', 'target□pro□by□watsons'),
        (1117, 'HARMONY', 'harmony'),
        (1120, 'L&P MEDIHEAL 美迪惠爾', 'lpmediheal'),
        (1120, 'L&P MEDIHEAL 美迪惠爾', 'l□p□mediheal'),
        (1120, 'L&P MEDIHEAL 美迪惠爾', '美迪惠爾'),
        (1123, 'Dr.Hsieh 達特醫', 'drhsieh'),
        (1123, 'Dr.Hsieh 達特醫', 'dr□hsieh'),
        (1123, 'Dr.Hsieh 達特醫', '達特醫'),
        (1126, 'LULULUN', 'lululun'),
        (1132, 'MYSCHEMING 我的心機', 'myscheming'),
        (1132, 'MYSCHEMING 我的心機', '我的心機'),
        (1138, 'MAYSKIN 優若美', 'mayskin'),
        (1138, 'MAYSKIN 優若美', '優若美'),
        (1141, 'N.A.F', 'naf'),
        (1141, 'N.A.F', 'n□a□f'),
        (1144, 'moonshot', 'moonshot'),
        (1147, 'Srichand 喜簪', 'srichand'),
        (1147, 'Srichand 喜簪', '喜簪'),
        (1150, 'PRETTIEAN 法國雅姿麗', 'prettiean'),
        (1150, 'PRETTIEAN 法國雅姿麗', '法國雅姿麗'),
        (1153, '080', '080'),
        (1156, 'PETALFRESH 沛特斯', 'petalfresh'),
        (1156, 'PETALFRESH 沛特斯', '沛特斯'),
        (1159, 'PINKGOGIRL Hey！蘋果肌女孩', 'pinkgogirlhey'),
        (1159, 'PINKGOGIRL Hey！蘋果肌女孩', 'pinkgogirl□hey'),
        (1159, 'PINKGOGIRL Hey！蘋果肌女孩', '蘋果肌女孩'),
        (1162, 'Reme+G 潤美肌', 'remeg'),
        (1162, 'Reme+G 潤美肌', 'reme□g'),
        (1162, 'Reme+G 潤美肌', '潤美肌'),
        (1165, 'SISTERDIARY 姊妹日記', 'sisterdiary'),
        (1165, 'SISTERDIARY 姊妹日記', '姊妹日記'),
        (1168, 'SKINBIOTEC 肌研生醫', 'skinbiotec'),
        (1168, 'SKINBIOTEC 肌研生醫', '肌研生醫'),
        (1171, 'SWEETHEARTBEAUTY 甜心美妝', 'sweetheartbeauty'),
        (1171, 'SWEETHEARTBEAUTY 甜心美妝', '甜心美妝'),
        (1174, 'TSAIO 上山採藥', 'tsaio'),
        (1174, 'TSAIO 上山採藥', '上山採藥'),
        (1177, 'Mistine', 'mistine'),
        (1180, 'PALTAC', 'paltac'),
        (1183, 'ZBYZIVA', 'zbyziva'),
        (1186, 'BENZAC', 'benzac'),
        (1192, 'Solone', 'solone'),
        (1198, 'La Formule 法國植萃合度', 'laformule'),
        (1198, 'La Formule 法國植萃合度', 'la□formule'),
        (1198, 'La Formule 法國植萃合度', '法國植萃合度'),
        (1204, 'Arome by Watsons', 'aromebywatsons'),
        (1204, 'Arome by Watsons', 'arome□by□watsons'),
        (1207, 'Rudy Profumi', 'rudyprofumi'),
        (1207, 'Rudy Profumi', 'rudy□profumi'),
        (1210, 'J.ONE', 'jone'),
        (1210, 'J.ONE', 'j□one'),
        (1213, 'SHELLEY and TEDDY', 'shelleyandteddy'),
        (1213, 'SHELLEY and TEDDY', 'shelley□and□teddy'),
        (1216, 'Pure Paw Paw', 'purepawpaw'),
        (1216, 'Pure Paw Paw', 'pure□paw□paw'),
        (1222, 'Reinachu 日本蕾娜啾', 'reinachu'),
        (1222, 'Reinachu 日本蕾娜啾', '日本蕾娜啾'),
        (1225, "Thailand bird's 泰國雙燕", 'thailandbird'),
        (1225, "Thailand bird's 泰國雙燕", 'thailandbirds'),
        (1225, "Thailand bird's 泰國雙燕", 'thailand□bird'),
        (1225, "Thailand bird's 泰國雙燕", 'thailand□birds'),
        (1225, "Thailand bird's 泰國雙燕", '泰國雙燕'),
        (1228, 'Goat', 'goat'),
        (1231, 'EVITA 艾薇塔', 'evita'),
        (1231, 'EVITA 艾薇塔', '艾薇塔'),
        (1243, 'STIVES 聖艾芙', 'stives'),
        (1243, 'STIVES 聖艾芙', '聖艾芙'),
        (1246, 'ROSYROSA', 'rosyrosa'),
        (1249, 'BECUPIDON 邱比特', 'becupidon'),
        (1249, 'BECUPIDON 邱比特', '邱比特'),
        (1252, 'LISTWISTEA', 'listwistea'),
        (1258, 'Bifesta', 'bifesta'),
        (1261, 'A-DERMA 艾芙美', 'aderma'),
        (1261, 'A-DERMA 艾芙美', 'a□derma'),
        (1261, 'A-DERMA 艾芙美', '艾芙美'),
        (1264, 'WONDER CORE', 'wondercore'),
        (1264, 'WONDER CORE', 'wonder□core'),
        (1267, 'YourHeart', 'yourheart'),
        (1270, 'FROMNATURE', 'fromnature'),
        (1273, 'Natracare', 'natracare'),
        (1279, 'VOO DOO', 'voodoo'),
        (1279, 'VOO DOO', 'voo□doo'),
        (1282, 'ESSENCE', 'essence'),
        (1285, 'evian 愛維養', 'evian'),
        (1285, 'evian 愛維養', '愛維養'),
        (1288, 'K-PALETTE', 'kpalette'),
        (1288, 'K-PALETTE', 'k□palette'),
        (1291, 'Love Ways 羅崴詩', 'loveways'),
        (1291, 'Love Ways 羅崴詩', 'love□ways'),
        (1291, 'Love Ways 羅崴詩', '羅崴詩'),
        (1294, 'Mori 水漾膜麗', 'mori'),
        (1294, 'Mori 水漾膜麗', '水漾膜麗'),
        (1297, 'COTA', 'cota'),
        (1300, 'coni beauty', 'conibeauty'),
        (1300, 'coni beauty', 'coni□beauty'),
        (1303, 'ZEYNABEAR', 'zeynabear'),
        (1306, 'TEAPOWER 茶寶', 'teapower'),
        (1306, 'TEAPOWER 茶寶', '茶寶'),
        (1312, '50惠', '50'),
        (1312, '50惠', '惠'),
        (1315, '美舒律', '美舒律'),
        (1336, 'BONANZA 寶藝', 'bonanza'),
        (1336, 'BONANZA 寶藝', '寶藝'),
        (1339, 'ELE', 'ele'),
        (1342, 'GATSBY', 'gatsby'),
        (1345, '俏佳人', '俏佳人'),
        (1348, 'GHOSTTOWASH', 'ghosttowash'),
        (1351, 'POINT', 'point'),
        (1369, 'RYO 呂', 'ryo'),
        (1369, 'RYO 呂', '呂'),
        (1375, 'LALIQUE', 'lalique'),
        (1378, 'SABON', 'sabon'),
        (1384, 'Alaïa', 'alaia'),
        (1387, 'GROWN ALCHEMIST', 'grownalchemist'),
        (1387, 'GROWN ALCHEMIST', 'grown□alchemist'),
        (1390, 'Domohorn Wrinkle 朵茉麗蔻', 'domohornwrinkle'),
        (1390, 'Domohorn Wrinkle 朵茉麗蔻', 'domohorn□wrinkle'),
        (1390, 'Domohorn Wrinkle 朵茉麗蔻', '朵茉麗蔻'),
        (1393, 'själ', 'sjal'),
        (1396, 'Graine de pastel', 'grainedepastel'),
        (1396, 'Graine de pastel', 'graine□de□pastel'),
        (1408, 'Äi Äi 曖曖。內含光', 'aiai'),
        (1408, 'Äi Äi 曖曖。內含光', 'ai□ai'),
        (1408, 'Äi Äi 曖曖。內含光', '曖曖內含光'),
        (1411, 'TKY', 'tky'),
        (1414, 'nooni', 'nooni'),
        (1417, 'bonvivant', 'bonvivant'),
        (1432, 'Nina Ricci', 'ninaricci'),
        (1432, 'Nina Ricci', 'nina□ricci'),
        (1447, 'Calvin Klein', 'calvinklein'),
        (1447, 'Calvin Klein', 'calvin□klein'),
        (1450, 'MALIN+GOETZ', 'malingoetz'),
        (1450, 'MALIN+GOETZ', 'malin□goetz'),
        (1453, 'uno', 'uno'),
        (1456, 'LAB SERIES 雅男士', 'labseries'),
        (1456, 'LAB SERIES 雅男士', 'lab□series'),
        (1456, 'LAB SERIES 雅男士', '雅男士'),
        (1462, 'Skinfood', 'skinfood'),
        (1465, 'Derma Formula 美肌醫生', 'dermaformula'),
        (1465, 'Derma Formula 美肌醫生', 'derma□formula'),
        (1465, 'Derma Formula 美肌醫生', '美肌醫生'),
        (1468, 'MDNA SKIN', 'mdnaskin'),
        (1468, 'MDNA SKIN', 'mdna□skin'),
        (1471, 'GLAMGLOW', 'glamglow'),
        (1477, 'ROHTO 日本樂敦', 'rohto'),
        (1477, 'ROHTO 日本樂敦', '日本樂敦'),
        (1480, 'STOP THE WATER WHILE USING ME!', 'stopthewaterwhileusingme'),
        (1480, 'STOP THE WATER WHILE USING ME!', 'stop□the□water□while□using□me'),
        (1489, '和田 LAND', 'land'),
        (1489, '和田 LAND', '和田'),
        (1492, 'Le Mini Macaron 迷你馬卡龍', 'leminimacaron'),
        (1492, 'Le Mini Macaron 迷你馬卡龍', 'le□mini□macaron'),
        (1492, 'Le Mini Macaron 迷你馬卡龍', '迷你馬卡龍'),
        (1495, 'elis 愛麗思', 'elis'),
        (1495, 'elis 愛麗思', '愛麗思'),
        (1498, 'ADDICTION 奧可玹', 'addiction'),
        (1498, 'ADDICTION 奧可玹', '奧可玹'),
        (1501, 'TOM FORD', 'tomford'),
        (1501, 'TOM FORD', 'tom□ford'),
        (1519, 'StriVectin 皺效奇蹟', 'strivectin'),
        (1519, 'StriVectin 皺效奇蹟', '皺效奇蹟'),
        (1522, 'ReFa 黎琺', 'refa'),
        (1522, 'ReFa 黎琺', '黎琺'),
        (1525, 'Natura Bissé', 'naturabisse'),
        (1525, 'Natura Bissé', 'natura□bisse'),
        (1528, 'su:m37° 甦秘', 'sum37'),
        (1528, 'su:m37° 甦秘', 'su□m37'),
        (1528, 'su:m37° 甦秘', '甦秘'),
        (1531, 'LAPCOS', 'lapcos'),
        (1534, 'NYX', 'nyx'),
        (1540, 'excel', 'excel'),
        (1543, 'beauty blender', 'beautyblender'),
        (1543, 'beauty blender', 'beauty□blender'),
        (1555, 'Christophe Robin', 'christopherobin'),
        (1555, 'Christophe Robin', 'christophe□robin'),
        (1558, 'AVON 雅芳', 'avon'),
        (1558, 'AVON 雅芳', '雅芳'),
        (1561, 'LUNASOL', 'lunasol'),
        (1576, 'nia', 'nia'),
        (1579, 'FORTE 台塑生醫', 'forte'),
        (1579, 'FORTE 台塑生醫', '台塑生醫'),
        (1582, 'Keune Care 肯葳', 'keunecare'),
        (1582, 'Keune Care 肯葳', 'keune□care'),
        (1582, 'Keune Care 肯葳', '肯葳'),
        (1588, 'Dr.Ci:Labo 城野醫生', 'drcilabo'),
        (1588, 'Dr.Ci:Labo 城野醫生', 'dr□ci□labo'),
        (1588, 'Dr.Ci:Labo 城野醫生', '城野醫生'),
        (1591, 'White Factor 白因子', 'whitefactor'),
        (1591, 'White Factor 白因子', 'white□factor'),
        (1591, 'White Factor 白因子', '白因子'),
        (1600, 'SUGAO', 'sugao'),
        (1609, 'PeterThomasRoth 彼得羅夫', 'peterthomasroth'),
        (1609, 'PeterThomasRoth 彼得羅夫', '彼得羅夫'),
        (1612, 'ANNY', 'anny'),
        (1615, 'OFRA Cosmetics', 'ofracosmetics'),
        (1615, 'OFRA Cosmetics', 'ofra□cosmetics'),
        (9000, 'Bio oil 百洛', 'biooil'),
        (9000, 'Bio oil 百洛', 'bio□oil'),
        (9000, 'Bio oil 百洛', '百洛'),
        (9002, 'CORSICA 科皙佳', 'corsica'),
        (9002, 'CORSICA 科皙佳', '科皙佳'),
        (9004, 'Covermark', 'covermark'),
        (9006, 'HACCI', 'hacci'),
        (9007, 'LUDEYA 露蒂雅', 'ludeya'),
        (9007, 'LUDEYA 露蒂雅', '露蒂雅'),
        (9009, 'MUJI 無印良品', 'muji'),
        (9009, 'MUJI 無印良品', '無印良品'),
        (9010, 'Mdmmd. 明洞國際', 'mdmmd'),
        (9010, 'Mdmmd. 明洞國際', '明洞國際'),
        (9011, 'PURE', 'pure'),
        (9012, 'Panatec 沛莉緹', 'panatec'),
        (9012, 'Panatec 沛莉緹', '沛莉緹'),
        (9014, 'TSZJITSUEI 瓷肌萃', 'tszjitsuei'),
        (9014, 'TSZJITSUEI 瓷肌萃', '瓷肌萃'),
        (9015, 'White', 'white'),
        (9017, 'motives 莫蒂膚', 'motives'),
        (9017, 'motives 莫蒂膚', '莫蒂膚'),
        (9018, '御泥坊', '御泥坊'),
    ]
